#!/usr/bin/env python3
import argparse
import logging
import lib.rsa as rsa

DESC = '''
Decrypt encrypted file/folder
'''
EX = '''
EX: %(prog)s file -k ~/.enc/rsa.key -p password
'''


def main(args):
    logging.basicConfig(level=logging.DEBUG if args.verbose else logging.INFO)
    return


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=DESC, epilog=EX)
    parser.add_argument('file', nargs='+',
                        help='file to be decrypted')
    parser.add_argument('-k', '--key',
                        help='private key used for decryption')
    parser.add_argument('-p', '--passphrase',
                        help='passphrase used with private key')
    parser.add_argument('-v', '--verbose', action='store_true',
                        help='enable verbose mode')
    args = parser.parse_args()
    main(args)
